# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-06-07 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20170606_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercheckout',
            name='email',
            field=models.EmailField(max_length=120, unique=True),
        ),
    ]
