# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-20 22:50
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('hd', 'HD'), ('sd', 'SD'), ('micro', 'Micro')], default='sd', max_length=12)),
                ('height', models.CharField(blank=True, max_length=10, null=True)),
                ('width', models.CharField(blank=True, max_length=10, null=True)),
                ('media', models.ImageField(blank=True, height_field=models.CharField(blank=True, max_length=10, null=True), null=True, upload_to=products.models.thumbnail_location, width_field=models.CharField(blank=True, max_length=10, null=True))),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='media',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Repo\\portfolio\\portfolio\\static_in_env\\protected'), upload_to=products.models.download_media_location),
        ),
        migrations.AddField(
            model_name='thumbnail',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
