# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-20 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170220_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='type',
            field=models.CharField(choices=[('hd', 'HD'), ('sd', 'SD'), ('micro', 'Micro')], default='hd', max_length=12),
        ),
    ]
