# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-20 23:47
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20170221_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='media',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to=products.models.thumbnail_location, width_field='width'),
        ),
    ]
