# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-21 12:18
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20170221_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='media',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\PyRepo\\Repo\\portfolio\\portfolio\\static_in_env\\protected'), upload_to=products.models.download_media_location),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='type',
            field=models.CharField(choices=[('hd', 'HD'), ('sd', 'SD'), ('micro', 'Micro')], max_length=12),
        ),
    ]
