# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-23 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20170223_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('sub_description', models.CharField(blank=True, max_length=1080, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=25)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('sale_active', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
    ]
