# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-25 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_myuuidmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUUIDModel',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
