# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-01 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20170301_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('out_of_stock', 'Out of stock'), ('inactive', 'Inactive')], default='active', max_length=30),
        ),
    ]
