# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-20 11:53
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('media', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\PyRepo\\Repo\\portfolio\\portfolio\\static_in_env\\protected'), upload_to=products.models.download_media_location)),
                ('price', models.DecimalField(decimal_places=2, max_digits=25)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=25, null=True)),
                ('sale_active', models.BooleanField(default=False)),
            ],
        ),
    ]
